#!/bin/sh

function update () {
    xsetroot -name "v: $(pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')%"
}

case "$1" in 
    toggle) amixer sset Master toggle && updatebar ;;
    up) amixer sset Master 5%+ && updatebar ;;
    down) amixer sset Master 5%- && updatebar ;;
esac > /dev/null

