#!/bin/sh

case "$1" in 
    info) upower -i /org/freedesktop/UPower/devices/battery_BAT0  ;;
    percentage) upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep -oE -m 1 '[0-9]+%' ;;
    *) echo "give an argument" ;;
esac 
