#!/bin/sh

battery=$( battery percentage )
volume=$(pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')%
xsetroot -name " v: $volume b: $battery $( date +"%R %F" ) "

